version: '3.7'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
    - db

  db:
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data: