version: '3.7'

services:

  api:
    container_name: api_container
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
    - db

  db:
    container_name: db_container
    image: postgres:11-alpine
    environment:
        POSTGRES_PASSWORD: key_to_the_kingdom
        POSTGRES_USER: mycoll
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

#  broker:
#    image: rabbitmq:3.9-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"

volumes:
    postgres_data:
    pgadmin_data: