version: '3.7'

services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
    - db

  db:
    image: postgres:11-alpine
    environment:
        POSTGRES_PASSWORD: key_to_the_kingdom
        POSTGRES_USER: mycoll
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  broker:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
    postgres_data: