"""Add MovieCopy table

Revision ID: 03bf01236a89
Revises: d987287b3fc4
Create Date: 2022-02-06 10:46:24.463831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03bf01236a89"
down_revision = "d987287b3fc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_copies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movie", sa.Integer(), nullable=True),
        sa.Column("owner", sa.Integer(), nullable=True),
        sa.Column("platform", sa.String(length=255), nullable=True),
        sa.Column("form", sa.String(length=255), nullable=True),
        sa.Column("vod_link", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["movie"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movie_copies_id"), "movie_copies", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movie_copies_id"), table_name="movie_copies")
    op.drop_table("movie_copies")
    # ### end Alembic commands ###
