"""01 add movie table

Revision ID: acb88292bb81
Revises: 
Create Date: 2022-01-17 14:30:31.326169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acb88292bb81"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("mpaa_rating", sa.String(length=255), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_id"), "movies", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movies_id"), table_name="movies")
    op.drop_table("movies")
    # ### end Alembic commands ###
