"""Adds relationship between Movie and User

Revision ID: d987287b3fc4
Revises: fa7b7bee6b26
Create Date: 2022-01-30 14:13:07.669520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d987287b3fc4"
down_revision = "fa7b7bee6b26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "movies", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movies", type_="foreignkey")
    op.drop_column("movies", "owner_id")
    # ### end Alembic commands ###
