"""Add MyCollUser table

Revision ID: f63a501722fe
Revises: 6c66b0c78ef3
Create Date: 2022-01-16 11:16:01.618850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63a501722fe'
down_revision = '6c66b0c78ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mycoll_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mycoll_users_id'), 'mycoll_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mycoll_users_id'), table_name='mycoll_users')
    op.drop_table('mycoll_users')
    # ### end Alembic commands ###
