"""Add default to User.disabled

Revision ID: fa7b7bee6b26
Revises: a2e1a00fde1a
Create Date: 2022-01-29 13:47:09.550274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7b7bee6b26'
down_revision = 'a2e1a00fde1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
